import "./globals.css";
import Script from "next/script";
import ClientLayout from "./cliendLayout";


export const metadata = {
  title: "OpenLearn",
  description: "Generated by create next app",
  icons: {
    icon: "favicon.ico",
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head>
        <link rel="stylesheet" href="/css/style.css" precedence="default" />
      </head>
      <body>   
          <ClientLayout>
          {children}
          </ClientLayout>
        <Script src="js/script.js" />
      </body>
    </html>
  );
}
