version: '3.8'

services:
  frontend:
    build: ./openlearn_njs/
      # context: ./openlearn_njs/
      # args:
      #   - PUBLIC_API_URL=http://backend:8000
    container_name: opl_frontend
    ports:
      - 3000:3000
    volumes:
      - ./openlearn_njs:/app
      - /app/node_modules
    environment:
      - PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - backend
    networks:
      - app-network
    command: sh -c "npm run build && npm start"
  
  backend:
    build: ./openlearn_django/
    container_name: opl_backend
    ports:
      - 3001:8000
    volumes:
      - ./openlearn_django/:/app
    environment:
      - DEBUG=0
    # depends_on:
    #   - db
    networks:
      - app-network
    command: >
      sh -c "python manage.py migrate &&
             gunicorn openlearn_django.wsgi:application --bind 0.0.0.0:8000"

  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: mydb
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data  # Persists data
  #   networks:
  #     - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local