# Generated by Django 5.2 on 2025-05-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0002_usermodel_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
    ]
