# Generated by Django 5.0.4 on 2025-05-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_videomodel_detail'),
        ('user_service', '0003_remove_usermodel_email_remove_usermodel_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='save_course',
            field=models.ManyToManyField(blank=True, to='courses.coursemodel'),
        ),
    ]
