# Generated by Django 5.0.4 on 2025-05-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0005_alter_usermodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
