# Generated by Django 5.0.4 on 2025-05-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_videomodel_detail'),
        ('user_service', '0008_alter_usermodel_save_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='save_course',
            field=models.ManyToManyField(blank=True, related_name='user_save', to='courses.coursemodel'),
        ),
    ]
