# Generated by Django 5.2 on 2025-05-05 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_service', '0009_alter_usermodel_save_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='profile',
        ),
    ]
