# Generated by Django 5.2 on 2025-05-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_videomodel_duration_coursemodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemodel',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videomodel',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
