# Generated by Django 5.2 on 2025-05-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_coursemodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='img',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
