# Generated by Django 5.2 on 2025-05-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursemodel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
