# Generated by Django 5.0.4 on 2025-05-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_videomodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='detail',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
